import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';
import { pathToFileURL } from 'node:url';
import { config } from '../server/config.mjs';
import { createApp } from '../server/app.mjs';

// Uses an installed Playwright, supplied explicitly or via the bundled desktop runtime.
const modulePath=process.env.PLAYWRIGHT_MODULE || path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const { chromium }=await import(pathToFileURL(modulePath).href);
const out=path.join(config.root,'artifacts','browser');await fs.mkdir(out,{recursive:true});
const dataDir=await fs.mkdtemp(path.join(out,'state-'));
const app=createApp({...config,dataDir});
// UI-only result fixture in disposable state: proposal evidence must never
// mark the original checkout's API card as passing.
app.store.run('INSERT INTO runs(id,kind,label,status,target_task,created_at) VALUES(?,?,?,?,?,?)','run_ui_proposal_fixture','qa','api','succeeded','task_ui_proposal_fixture',new Date().toISOString());
await new Promise(r=>app.server.listen(0,'127.0.0.1',r));await app.ready;
const url=`http://127.0.0.1:${app.server.address().port}`;
const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL || 'msedge'});
const page=await browser.newPage({viewport:{width:1440,height:1050},deviceScaleFactor:1});
const errors=[];page.on('pageerror',error=>errors.push(error.message));
page.on('console',message=>{if(message.type()==='error') errors.push(message.text());});
try {
  await page.goto(url);await page.getByRole('heading',{name:'Your maintenance, in focus.'}).waitFor();
  await page.screenshot({path:path.join(out,'overview-desktop.png'),fullPage:true});
  await page.getByRole('button',{name:'New request',exact:false}).click();
  await page.getByLabel('Request title').fill('Smoke test: portal permission review');
  await page.getByLabel('What needs to happen?').fill('Review company portal access rules. This is a UI test request; do not execute an AI run.');
  await page.getByLabel('Product area',{exact:true}).selectOption('Portal');
  await page.getByRole('button',{name:'Create request',exact:false}).click();
  await page.locator('#detail-dialog[open]').waitFor();
  await page.getByLabel('Follow-up message').fill('Preserve tenant boundaries and existing grants.');
  await page.getByRole('button',{name:'Add',exact:true}).click();
  await page.getByText('Preserve tenant boundaries and existing grants.',{exact:true}).waitFor();
  await page.locator('#detail-dialog').getByRole('button',{name:'Close',exact:true}).click();
  await page.getByRole('button',{name:/Smoke test: portal permission review/}).first().waitFor();
  assert.equal(await page.locator('.work-card').count(),4);
  await page.screenshot({path:path.join(out,'work-board.png'),fullPage:true});
  await page.getByRole('link',{name:'Repository & docs'}).click();
  await page.getByRole('heading',{name:'Nexora, grounded in source.'}).waitFor();
  await page.getByLabel('Search repository files').fill('LOCAL-TESTING');
  await page.getByRole('button',{name:'Search source',exact:true}).click();
  await page.locator('.file-result').first().waitFor();
  await page.locator('.file-result').first().click();
  await page.locator('#reader-dialog[open]').waitFor();
  assert.match(await page.locator('#reader-content').textContent(),/SQL Express/);
  await page.locator('#reader-dialog').getByRole('button',{name:'Close',exact:true}).click();
  await page.getByRole('link',{name:'QA & verification'}).click();
  await page.getByRole('heading',{name:'Evidence over assumptions.'}).waitFor();
  assert.equal(await page.getByRole('button',{name:'Run check'}).count(),6);
  await page.locator('.qa-card').filter({has:page.getByRole('heading',{name:'API regression',exact:true})}).getByText('Not run',{exact:true}).waitFor();
  await page.screenshot({path:path.join(out,'qa-desktop.png'),fullPage:true});
  await page.getByRole('link',{name:'AI team'}).click();
  await page.getByRole('heading',{name:'A team built around Nexora'}).waitFor();
  assert.equal(await page.locator('.agent-directory .agent-card').count(),6);
  await page.getByRole('link',{name:'Workspace settings'}).click();
  await page.getByRole('heading',{name:'Usage and maintenance'}).waitFor();
  await page.getByRole('button',{name:'Create backup',exact:true}).click();
  await page.getByRole('heading',{name:'Backup created',exact:true}).waitFor();
  await page.locator('#reader-dialog').getByRole('button',{name:'Close',exact:true}).click();
  await page.getByRole('button',{name:'Review cleanup',exact:true}).click();
  await page.getByRole('heading',{name:'Review expired workspace cleanup'}).waitFor();
  assert.match(await page.locator('#reader-content').textContent(),/No expired/);
  await page.locator('#reader-dialog').getByRole('button',{name:'Close',exact:true}).click();
  await page.screenshot({path:path.join(out,'operations-settings.png'),fullPage:true});
  await page.getByRole('link',{name:'Overview',exact:false}).click();
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(out,'overview-mobile.png'),fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false,'Mobile page must not overflow');
  await page.reload();await page.getByRole('heading',{name:'Your maintenance, in focus.'}).waitFor();
  await page.getByRole('link',{name:'Work board'}).click();
  await page.locator('.work-card').first().waitFor();
  assert.equal(await page.locator('.work-card').count(),4,'Tasks must survive reload');
  await page.getByRole('link',{name:'AI team'}).click();
  await page.getByRole('button',{name:/Nexora Support Agent/}).click();
  assert.equal(await page.locator('#agent-select').inputValue(),'support');
  const workflow=page.locator('#request-form [name=workflow]');
  assert.equal(await workflow.isEnabled(),true);
  assert.equal(await workflow.isChecked(),false,'Support defaults to standalone triage');
  await page.getByLabel('Request title').fill('Support smoke: CRM investigation');
  await page.getByLabel('What needs to happen?').fill('Investigate a reported CRM issue; UI test only, do not execute agents.');
  await page.getByLabel('Product area',{exact:true}).selectOption('CRM');
  await workflow.check();
  await page.getByRole('button',{name:'Create request',exact:false}).click();
  await page.locator('#detail-dialog[open]').waitFor();
  await page.locator('#detail-dialog').getByRole('button',{name:'Close',exact:true}).click();
  assert.equal(await page.locator('.work-card').count(),8,'Support workflow adds support, BA, developer and QA');
  assert.deepEqual(errors,[]);
  console.log('PASS: desktop/mobile rendering, workflow creation, conversation persistence, source search/document reader, six agents, QA catalog, no page errors or mobile overflow.');
  console.log(`Screenshots: ${out}`);
} finally { await browser.close();await app.close(); }
