export const areas = ['All Nexora', 'CRM', 'Portal', 'Website / CMS', 'Platform'];
export const agents = [
  { id: 'pm', name: 'Project Manager', initials: 'PM', color: 'violet', specialty: 'Scope & delivery', description: 'Turn maintenance requests into bounded work, dependencies and acceptance criteria.', instruction: 'Evaluate impact and scope. Produce a prioritized backlog, dependencies, risks and observable acceptance criteria. Do not claim implementation. Explain the next BA/developer/QA handoff.' },
  { id: 'ba', name: 'Business Analyst', initials: 'BA', color: 'blue', specialty: 'Requirements & knowledge', description: 'Trace existing behavior to source and write functional specifications.', instruction: 'Inspect relevant source and docs. Produce a client-readable functional requirements document: problem, current behavior with file and line references, intended behavior, business rules, permission boundaries, acceptance criteria, exclusions and open questions. Distinguish inference from verified code behavior.' },
  { id: 'crm_dev', name: 'CRM Developer', initials: 'CD', color: 'teal', specialty: 'CRM & shared services', description: 'Maintain CRM, APIs, membership rules and shared module contracts.', instruction: 'Implement the bounded request in this isolated workspace. Follow AGENTS.md and existing .NET/EF/Next.js conventions. Preserve tenant and permission boundaries and shared BuildingBlocks contracts. Avoid cross-module database access. Explain changed files, verification and remaining limitations. Never commit, push or deploy.' },
  { id: 'portal_dev', name: 'Portal Developer', initials: 'PD', color: 'orange', specialty: 'Portal & website', description: 'Maintain member journeys, portal access and CMS presentation.', instruction: 'Implement the bounded Portal/Website request in this isolated workspace. Follow AGENTS.md. Reuse shared CRM, portal and CMS services. Validate principal, tenant, Contact, active grant and Account. Do not enable production identity, email or payments. Explain changed files, tests and unverified surfaces. Never commit, push or deploy.' },
  { id: 'qa', name: 'QA Engineer', initials: 'QA', color: 'pink', specialty: 'Regression & evidence', description: 'Create focused regression tests and inspect verification evidence.', instruction: 'Inspect the request and implementation. Create focused regression tests using existing xUnit and Playwright conventions in this isolated workspace when appropriate. Report exact commands and distinguish test files created, tests executed, passes, failures and not-run checks. Never invent passing results. Do not start production services or access a live database.' },
  { id: 'support', name: 'Nexora Support Agent', initials: 'SP', color: 'slate', specialty: 'Nexora support & triage', description: 'Investigate Nexora CRM, Portal and CMS issues, explain supported solutions and prepare reviewed engineering handoffs.', instruction: 'Handle Nexora support requests across CRM, membership, Portal, Website/CMS and shared platform services. Inspect source and documentation in this isolated copy. Classify the request as how-to, suspected defect, configuration issue or enhancement. Report affected area, user impact and severity with rationale, expected versus observed behavior, reproducible steps, verified evidence with source references, hypotheses, missing information, and safe documented guidance where available. Never invent reproduction or resolution. Do not ask for passwords, tokens or personal member data; request redacted diagnostics only. For engineering work, give the BA a concise handoff with acceptance criteria and regression risks. For guidance-only requests, explain the answer and state whether user confirmation is still needed. Draft a plain-language support response for review, but never send it. Remain read-only: do not change code, configuration, credentials, memberships, permissions or live data. Do not claim a fix or close an issue merely because this report is complete.' },
];
export const suites = [
  { id: 'architecture', name: 'Architecture checks', area: 'Platform', detail: 'xUnit module and assembly conventions. No application database required.', timeout: 300000, kind: 'dotnet', args: ['test', 'backend/tests/Nexora.Architecture.Tests/Nexora.Architecture.Tests.csproj', '--nologo', '--verbosity', 'minimal'] },
  { id: 'api', name: 'API regression', area: 'Platform', detail: 'Full Nexora API test project. Requires its configured test dependencies.', timeout: 900000, kind: 'dotnet', args: ['test', 'backend/tests/Nexora.Api.Tests/Nexora.Api.Tests.csproj', '--nologo', '--verbosity', 'minimal'] },
  { id: 'crm', name: 'CRM browser journey', area: 'CRM', detail: 'Production frontend, isolated SQL test database, ports 5095 / 3015.', timeout: 1800000, kind: 'node', args: ['scripts/Test-Website.mjs', '--crm', '--production'] },
  { id: 'portal', name: 'Portal browser journeys', area: 'Portal', detail: 'Personal and company portal flows in an isolated SQL test database.', timeout: 1800000, kind: 'node', args: ['scripts/Test-Website.mjs', '--portal', '--production'] },
  { id: 'website', name: 'Website / CMS journey', area: 'Website / CMS', detail: 'Publishing and website behavior against the production frontend.', timeout: 1800000, kind: 'node', args: ['scripts/Test-Website.mjs', '--production'] },
  { id: 'integrated', name: 'Integrated acceptance', area: 'All Nexora', detail: 'CRM, Portal and CMS together. Uses Nexora’s existing disposable database runner.', timeout: 1800000, kind: 'node', args: ['scripts/Test-Website.mjs', '--all', '--production'] },
];
